name: Watermark Images and Deploy Jekyll Site

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0' # Use a compatible Ruby version
        bundler: '2.4.22' # Specify a compatible Bundler version

    - name: Install Jekyll and dependencies
      run: |
        rm -f Gemfile.lock # Remove old lockfile to force regeneration with compatible Bundler
        bundle install
      working-directory: nitinnat.github.io

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Run image watermarking script
      if: steps.changes.outputs.images == 'true' || steps.changes.outputs.experience_images == 'true'
      run: ruby watermark_images.rb
      working-directory: nitinnat.github.io

    - name: Build Jekyll site
      run: bundle exec jekyll build
      working-directory: nitinnat.github.io

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: master
